[package]
name = "git-report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
regex = "1"
lazy_static = "1"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
datafusion = "6"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync", "parking_lot"] }
serde_yaml = "0.8"
async-trait = "0.1"
async-process = "1"
futures = "0.3"
chrono = "0.4"
github-rs = "0.7"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
humantime = "2"
