[package]
name = "git-pannel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
regex = "1"
lazy_static = "1"
snafu = "0.7"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
datafusion = "6"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync", "parking_lot"] }
