author_mappings:
  - source:
      name: "dongdongx"
      email: "chenjiandongx@qq.com"
    destination:
      name: "chenjiandongx"
      email: "chenjiandongx@qq.com"
  - source:
      name: "陈键冬"
      email: "chenjiandongx@qq.com"
    destination:
      name: "chenjiandongx"
      email: "chenjiandongx@qq.com"
  - source:
      name: "dongdong"
      email: "chenjiandongx@qq.com"
    destination:
      name: "chenjiandongx"
      email: "chenjiandongx@qq.com"
  - source:
      name: "dingdongx"
      email: "chenjiandongx@qq.com"
    destination:
      name: "chenjiandongx"
      email: "chenjiandongx@qq.com"

databases:
  - name: "dongdongx"
    directory: "./data"
    mode: "clone"
    repositories:
      - name: "pyecharts/pyecharts"
        remote: "https://github.com/pyecharts/pyecharts.git"
        path: "/Users/chenjiandongx/project/python/pyecharts"
      - name: "cutecharts/cutecharts"
        remote: "https://github.com/cutecharts/cutecharts.git"
        path: "/Users/chenjiandongx/project/python/cutecharts"
